name = "bing-verifier"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-06-04"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"

[[kv_namespaces]]
binding = "BING_SITE_AUTHS"
id = "96890ebc919e4888952814ad596e2bd9"
preview_id = "96890ebc919e4888952814ad596e2bd9"
